__all__ = [
    "create_labels",
    "create_widgets",
    "custom_color",
    "custom_font",
    "end_screen",
    "input",
    "load_config",
    "main",
    "random_word",
    "start_screen",
    "styling",
    "update_board",
    "validate",
    "WORDLE",
]
